# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4615f5cf16594dfe2ca6b5f6a38ad318ead88b10842434191aafa36a3f9960435598ef5adef9b26ec5bb7530bfd98350fa21ec1bd8cbd50d8dfda4ec0a4c125

test:
  secret_key_base: f67f865a1ed824739fc3ba53e962bf05e1c6b379e9b9a0ab03df39ab1e4849b132f7fe7cc81eb31347f5c67c7f6badad8f02d54f09701e4dd6788bf0f2a7c000

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
